### ISSUE TITLE
[webhook] reduce memory usage of the webhook

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#1152]
## Expected Behavior
Webhook memory usage should remain somewhat linear with the resources that are being **_watched_**

## Actual Behavior
@sravankumar777 reported high memory usage here: https://github.com/knative/serving/issues/7195

I think it's because our informers are watching _all_ secrets here: https://github.com/knative/pkg/blob/master/webhook/certificates/controller.go#L59

## Steps to Reproduce the Problem

1. See https://github.com/knative/serving/issues/7195

## Additional Info
We should ensure we're scoping other informers appropriately as well

**Comment by mattmoor** [comment]
There is an injection context function that can be used to scope the injected informers to a single namespace.  I think we'll also want the capacity to do this per-type as there are contexts where I could see us doing this for some types (Secrets, ConfigMaps) and not for others (Bindings).

**Comment by mattmoor** [comment]
It would be good to get a heap profile of what's going on in these situations too rather than just guessing 👼

**Comment by bbrowning** [comment]
Here's a screenshot of a heap profile for a case I recently ran into. If I'm reading it right, about 83% of the in_use heap space is from reading secrets from all over the cluster?
![Screenshot from 2020-03-11 14-29-49](https://user-images.githubusercontent.com/56071/76451007-21708f80-63a5-11ea-9c4a-87d4843fd62a.png)

**Comment by mattmoor** [comment]
@bbrowning can you confirm that this is fixed at HEAD?

**Comment by mattmoor** [comment]
cc @markusthoemmes

**Comment by dprotaso** [comment]
PR that has the fix: https://github.com/knative/pkg/issues/1152 which is part of 0.14 serving release

**Comment by sravankumar777** [comment]
@dprotaso & @mattmoor, looks like the issue for webhook pod memory usage is not resolved with knative-serving v0.14.0 release.

Below are the memory usage dashboard for two different environment, on which knative-serving is deployed. 

<img width="1340" alt="webhook-memory-usage-1" src="https://user-images.githubusercontent.com/18139717/84020949-ac6e1f80-a9be-11ea-88b5-95690e3992e3.png">
<img width="1340" alt="webhook-memory-usage-2" src="https://user-images.githubusercontent.com/18139717/84020952-ae37e300-a9be-11ea-9375-cf62451773ef.png">

```
$ kubectl get pod webhook-c9cfb67b7-6q8nb -nknative-serving -o jsonpath='{range .spec.containers[*]}{.name}{"\t"}{.resources.limits}{"\n"}{end}'
webhook	map[cpu:200m memory:200Mi]
istio-proxy	map[cpu:2 memory:512Mi]
```

```
$ kubectl get pod webhook-c9cfb67b7-6q8nb -nknative-serving -o jsonpath='{range .spec.containers[*]}{.name}{"\t"}{.resources.requests}{"\n"}{end}'
webhook	map[cpu:20m memory:20Mi]
istio-proxy	map[cpu:50m memory:180Mi]
```

**Comment by dprotaso** [comment]
Thanks for the update @sravankumar777 

Is there anything happening in your cluster over that duration? ie. I believe @bbrowning's saw a similar issue when creating many namespaces.

**Comment by vagababov** [comment]
I verified that number of namespaces does not trigger this.
https://github.com/knative/pkg/pull/1158  — is definitely part of 0.14 branch.
Can you check that you indeed run 0.14 or newer?
Otherwise can you share what is done to the cluster? I.e. do you create lots of services or revisions or some other objects?

**Comment by sravankumar777** [comment]
@dprotaso & @vagababov, as mentioned earlier we do definitely around 300+ namespaces.
Apart from this, we do run e2e serving test continuouly from a testing namespace to monitor working of management components.

e2e serving test:
1. Create KSVC
2. Pod Autoscaling based on 30QPS on a KSVC.
3. Delete KSVC. 

This KSVC is always created with a random name on every instance. 
Plan to upgrade to v0.15.0 very soon. 

Thank you.

**Comment by vagababov** [comment]
I've just created 200 namespaces and noticed 0 uptick in memory. Let me try to do the same with creating a service in each.

**Comment by vagababov** [comment]
Did the same with creating a service in each
Still no memory change. I don't think this is knative specific issue (at least at head).

**Comment by vagababov** [comment]
Is this still an issue?

**Comment by dprotaso** [comment]
bump @sravankumar777
